INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_cha/INT_repair_mutation_for_greater_line_100.sol:INT:
INFO:symExec:Running, please wait...
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/root/osiris/z3/z3.py", line 137, in z3_error_handler
    def z3_error_handler(c, e):

  .oooooo.             o8o            o8o          
 d8P'  `Y8b            `"'            `"'          
888      888  .oooo.o oooo  oooo d8b oooo   .oooo.o
888      888 d88(  "8 `888  `888""8P `888  d88(  "8
888      888 `"Y88b.   888   888      888  `"Y88b. 
`88b    d88' o.  )88b  888   888      888  o.  )88b
 `Y8bood8P'  8""888P' o888o d888b    o888o 8""888P'


!!! SYMBOLIC EXECUTION TIMEOUT !!!
  File "/root/osiris/symExec.py", line 2868, in handler
    raise Exception("timeout")
Exception: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 85.9%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 True
//root/smartbugs/dataset/int_bugs_9/0604/repair_cha/INT_repair_mutation_for_greater_line_100.sol:INT:101:4
totalSupply -= _value
^
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 50.1404018402 seconds ---
INFO:symExec:	====== Analysis Completed ======
INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_cha/INT_repair_mutation_for_greater_line_100.sol:INTToken:
INFO:symExec:Running, please wait...
Traceback (most recent call last):
  File "/root/osiris/taintFlow.py", line 652, in perform_taint_analysis
    propagate_taint(taint, tainted_stack, tainted_memory, tainted_storage, instruction, current_stack, previous_block, current_block, next_blocks, arithmetic_errors, sha3_list, false_positives, strings)
  File "/root/osiris/taintFlow.py", line 308, in propagate_taint
    if not tainted_object in taint:
  File "/root/osiris/taintFlow.py", line 78, in __eq__
    return self.__dict__ == _other.__dict__
  File "/root/osiris/z3/z3.py", line 302, in __nonzero__
    return self.__bool__()
  File "/root/osiris/z3/z3.py", line 310, in __bool__
    return self.arg(0).eq(self.arg(1))
  File "/root/osiris/z3/z3.py", line 920, in arg
    _z3_assert(is_app(self), "Z3 application expected")
  File "/root/osiris/z3/z3.py", line 1077, in is_app
    k = _ast_kind(a.ctx, a)
  File "/root/osiris/z3/z3.py", line 418, in _ast_kind
    a = a.as_ast()
  File "/root/osiris/symExec.py", line 2868, in handler
    raise Exception("timeout")
Exception: timeout
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 85.9%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 True
//root/smartbugs/dataset/int_bugs_9/0604/repair_cha/INT_repair_mutation_for_greater_line_100.sol:INTToken:101:4
totalSupply -= _value
^
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 50.0482261181 seconds ---
INFO:symExec:	====== Analysis Completed ======
INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_cha/INT_repair_mutation_for_greater_line_100.sol:owned:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 99.4%
INFO:symExec:	  Arithmetic bugs: 	 False
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 False
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 0.267421007156 seconds ---
INFO:symExec:	====== Analysis Completed ======
INFO:root:Contract //root/smartbugs/dataset/int_bugs_9/0604/repair_cha/INT_repair_mutation_for_greater_line_100.sol:token:
INFO:symExec:Running, please wait...
INFO:symExec:	============ Results ===========
INFO:symExec:	  EVM code coverage: 	 95.5%
INFO:symExec:	  Arithmetic bugs: 	 True
INFO:symExec:	  └> Overflow bugs: 	 False
INFO:symExec:	  └> Underflow bugs: 	 True
//root/smartbugs/dataset/int_bugs_9/0604/repair_cha/INT_repair_mutation_for_greater_line_100.sol:token:101:4
totalSupply -= _value
^
INFO:symExec:	  └> Division bugs: 	 False
INFO:symExec:	  └> Modulo bugs:   	 False
INFO:symExec:	  └> Truncation bugs: 	 False
INFO:symExec:	  └> Signedness bugs: 	 False
INFO:symExec:	  Callstack bug: 	 False
INFO:symExec:	  Concurrency bug: 	 False
INFO:symExec:	  Time dependency bug: 	 False
INFO:symExec:	  Reentrancy bug: 	 False
INFO:symExec:	 --- 50.0596101284 seconds ---
INFO:symExec:	====== Analysis Completed ======
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored
Exception z3.z3types.Z3Exception: Z3Exception() in <object repr() failed> ignored

!!! SYMBOLIC EXECUTION TIMEOUT !!!
Unexpected error: <type 'exceptions.Exception'>


!!! SYMBOLIC EXECUTION TIMEOUT !!!